export const GETING_COMPETITIONS = "GETING_COMPETITIONS"
export const GET_COMPETITIONS_SUCCESS = "GET_COMPETITIONS_SUCCESS"
export const GET_COMPETITIONS_FAILURE = "GET_COMPETITIONS_FAILURE"
 
export const GETING_COMPETITORS = "GETING_COMPETITORS"
export const GET_COMPETITORS_SUCCESS = "GET_COMPETITORS_SUCCESS"
export const GET_COMPETITORS_FAILURE = "GET_COMPETITORS_FAILURE"

export const POSTING_COMPETITOR = "POSTING_COMPETITOR"
export const POSTED_COMPETITOR = "POSTED_COMPETITOR"